app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email=db.Column(db.String(255),unique=True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    blogs = db.relationship('Blog', backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic')
    pass_secure = db.Column(db.String(225))


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    description=db.Column(db.String)
    like = db.Column(db.Integer)
    dislike = db.Column(db.Integer)
    comment = db.relationship('Comment',backref='blog',lazy='dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls):
        '''
        gets blogs from the database
        '''
        blogs=Blog.query.all()

        return blogs

class Comment(db.Model):

    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key =True)
    comment = db.Column(db.String(255))
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    def delete_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id=id).all()
        return comments

    def __repr__(self):
        return f'Comment {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,PasswordField
from wtforms.validators import Required,Email,EqualTo
from ..models import User,Blog,Comment

class BlogForm(FlaskForm):

    name = StringField('Enter Blog Title ',validators=[Required()])
    description= TextAreaField('Enter Text ...')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = StringField('Comment: ', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask 
from flask_bootstrap import Bootstrap 
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # configure UploadSet
    configure_uploads(app,photos)

    #Configure email
    mail.init_app(app)

    #auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    return app
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from .views import *
from . import views,error

app/main/views.py
from flask import render_template,redirect,url_for,request,abort,flash
from flask_login import login_required,login_user,logout_user,current_user
from . import main
from app.models import User,Blog,Comment
from app.requests import get_quotes
from .forms import BlogForm,UpdateProfile,CommentForm
from .. import db,photos

@main.route('/')
def index():
    title = 'Home'

    quotes = get_quotes()
    blogs = Blog.get_blogs()
    
    

    return render_template('index.html' ,title=title, blogs=blogs, quote = quotes)

@main.route('/blog/new',methods=['GET','POST'])
@login_required
def new_blog():
    '''
    Method to add new blog
    '''
    form= BlogForm()
    if form.validate_on_submit():
        name =form.name.data
        description=form.description.data
        like=0
        dislike=0
        new_blog=Blog(name = name ,description=description,like=like,dislike=dislike)
        new_blog.save_blog()
        return redirect(url_for('.index'))

    title= 'Blogs'
    return render_template('blog.html',blog_form =form, title = title)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    '''
    Method to update profile picture
    '''
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))



@main.route('/blog/<blog_id>/update',methods=['GET','POST'])
@login_required
def update_blog(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(404)

    form = BlogForm()
    if form.validate_on_submit():
        blog.name= form.name.data
        blog.description = form.description.data
        db.session.commit()
        flash('You have updated your Blog')
    

        return redirect(url_for('main.index',id=blog_id))
    if request.method == 'GET':
        form.name.data = blog.name
        form.description.data = blog.description

    return render_template('blog.html',blog_form = form)

@main.route('/blog/<blog_id>/delete', methods=['POST'])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    db.session.delete(blog)
    db.session.commit()

    flash('You have deleted your Blog succesfully')
    return redirect(url_for('main.index'))

@main.route('/post/<int:blog_id>')
def post(blog_id):
    '''
    View root page function that returns the posts page and its data
    '''
    post = Blog.query.filter_by(id=blog_id).one()
    post_comments = Comment.get_comments(blog_id)
    title = '' 
    return render_template('post.html', title = title, post=post, post_comments=post_comments )
    
@main.route('/comment/<int:blog_id>',methods=['GET','POST'])
@login_required
def comment(blog_id):
    post = Blog.query.filter_by(id=blog_id).one()
    comment_form  = CommentForm()
    if  comment_form.validate_on_submit():
        new_comment = Comment(comment = comment_form.comment.data, user_id = current_user.id, blog_id=post.id)
        # new_comment.save_comment()
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('main.post',blog_id=post.id))
    
    return render_template('new_comment.html',comment_form= comment_form)

@main.route('/post/<post_id>')
def comm(post_id):
    post_comm = Comment.get_comment(post_id)

    return render_template('index.html' ,post_comm=post_comm)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
</head>

<body>
    <!-- Navbar block-->

    {% block navbar %}
    
    {% include 'navbar.html' %}

    {% endblock %} 
    {% block content %}

    {% endblock %}
</body>

</html>

app/templates/blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
{{ super() }}

<link rel="stylesheet" href="{{url_for('static', filename = 'css/index.css')}}">
{% endblock %}

{% block content %}

<body style="background-color: rgb(240, 209, 199)">


    <title> {{ title }} </title>

    <div class="container">

        <div class="row">

            <div class="col-md-2 col-lg-2">

            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">

                {{ wtf.quick_form(blog_form) }}

            </div>

            <!-- <div class="col-md-2 col-lg-2">
            <div class="row">
                <h3>Comments</h3>
                {% for comm in post_comm %}
                <p>{{ comm.comment }}</p>
                {% endfor %}
            </div>

        </div> -->

        </div>
    </div>
</body>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>Oh dear oh dear oh dear.....Seems like we can't find what you're looking for<br>But that's okay...It be like that
    sometimes</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}


{% block styles%}
{{ super() }}

<link rel="stylesheet" href="{{url_for('static', filename = 'css/index.css')}}">
{% endblock %}

{% block content %}

<body style="background-color: darksalmon">



    <title> {{ title }} </title>

    <div class="container">

        <div class="jumbotron" style="width: 100%; text-align:center; background-color:rgb(243, 172, 148)">
            <h2 class="blog-header" style="font-size: 70px">
                <strong>BLOG.ME</strong>
            </h2>
            
            <h4 class="card-text"><strong>A brainy Quote for you :</strong> <em >{{quote.quote}}</em></h4>
            <h5>~{{quote.author}}</h5>
            <p></p>

        </div>
        <br><br><br>
        <div class="row">

            <div class="col-md-4 col-lg-4">
                <h2 class="blog-create"> <a href="/blog/new"> Write your own blog post.</a></h2>
            </div>

        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6" style="font-size: 15px" >
                {% for blog in blogs %}
                <div class="card" style="background-color:rgb(230, 194, 182); margin-top: 10px; width: 800px;">
                    <div class="card-header" style="font-size: 30px; margin-left:10px;">{{ blog.name }}</div>
                    <p class="card-title" style="font-size: 25px; margin-left:10px;">{{blog.description}}</p>
                    <div class="card-footer">
                        <a href="/blog_vote/{{blog.id}}?like=1">Like: {{blog.like}}</a>
                        <a href="/blog_vote/{{blog.id}}?dislike=1">Dislike: {{blog.dislike}}</a>
                        <button style="margin-bottom: 10px"> <a href="{{url_for('main.comment', blog_id = blog.id)}}">Add Comment</a></button>
                        <button> <a href="{{url_for('main.post', blog_id = blog.id)}}">View Comment</a></button>
                        {% if current_user.is_authenticated %}
                        <div>

                            <a class="btn btn-secondary btn-sm mt-1 mb-1"
                                href="{{ url_for('main.update_blog', blog_id=blog.id) }}">Update</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                                data-target="#deleteModal">Delete</button>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor%}
            </div>
        </div>
    </div>

</body>

{% endblock %}

app/templates/navbar.html
<style>
    .container-fluid{
    background-color:rgba(5, 4, 5, 0.822);
    color: black;
      }
    </style>
    <div class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"> BLOG.ME</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>

                        {% if current_user.is_authenticated %}
                        <li style="color:white;padding:15px;"><{{current_user.username}}</li>
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                      {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                      {% endif %}  

                </div>
    
            </div>
    </div>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
{{ super() }}

<link rel="stylesheet" href="{{url_for('static', filename = 'css/index.css')}}">
{% endblock %}

{% block content %}

<body style="background-color: rgb(219, 174, 159)">


    <title> {{ title }} </title>

    <div class="container">

        <div class="row">

            <div class="col-md-2 col-lg-2">

            </div>


            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">

                {{ wtf.quick_form(comment_form) }}


            </div>

            <div class="col-md-2 col-lg-2">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}

                </div>
                {% endfor %}

            </div>

        </div>
    </div>
</body>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}

{% block styles%}
{{ super() }}

<link rel="stylesheet" href="{{url_for('static', filename = 'css/index.css')}}">
{% endblock %}

{% block content %}

<body style="background-color:darksalmon">
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <h3 style="font-size: 45px">COMMENTS:</h3>
                    <hr style="font-size: 25px; font-family:Arial, Helvetica, sans-serif">
                    {% for comment in post_comments %}
                    <p>{{comment.comment}}</p>
                    <hr>
                    {% endfor%}
                </div>

            </div>
        </div>
    </article>
    <hr>
</body>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}

            <p>You don't have a profile <picture></picture></p>
            {% endif %}

            {% if user == current_user %}

            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
                
            </form>
            {% endif %}
        </div>

        {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}">Update profile</a>
        {% endif %}

    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}